### ISSUE TITLE
Make available tables and columns visible

### ISSUE THREAD

**Issue by linag-0** [data-hydenv/hydenv-database#20]
as discussed in slack, it may be very useful to actually see which tables are in the database and therefore available for analyses.

**Comment by modche** [comment]
To have a "clean" issue here, could you add a screenshot of the slack discussion here or give more details? Otherwise that would be a little bit tricky to understand what you mean here.... I think linking Slack issues is not possible here due to the login requirements of Slack.

**Comment by mmaelicke** [comment]
What we basically want in the exercises application is somthing like this:

![image](https://user-images.githubusercontent.com/2826034/104576966-379c4b80-5659-11eb-9180-bc593b8eb2fe.png)

@linag-0  can you confirm, that this is what you had in mind?

**Comment by linag-0** [comment]
hello, this looks exactly like what I had in mind!
The slack conversation should be attached here 
![grafik](https://user-images.githubusercontent.com/77098218/104583543-8b129780-5661-11eb-8d06-d91f358b5a49.png)

**Comment by mmaelicke** [comment]
Thank you!
The current roadmap is to implement this over the weekend.

**Comment by JL-Rosien** [comment]
Thank you very much! That would be very helpful since I get the error messenge "(psycopg2.errors.SyntaxError) FEHLER: Syntaxfehler bei »SELECT« LINE 2: SELECT * FROM pg_catalog.pg_tables WHERE schemaname='public' ^ [SQL: SELECT count(*) AS amount FROM metadata SELECT * FROM pg_catalog.pg_tables WHERE schemaname='public'] (Background on this error at: http://sqlalche.me/e/13/f405)" in the CLI. Am currently trying to make it work in RStudio

**Comment by mmaelicke** [comment]
How do you try to use the hydenv CLI in RStudio? These are two different applications. In RStudio you can use the `dbListTables` command from the `RPostgreSQL` package.

**Comment by JL-Rosien** [comment]
ah sorry for my unprecise formulation. To use the  "dbListTables" command  from the "RPostgreSQL" package in RStudion is what I meant. I am aware though that RStudio ist otherwise not the way to go for further coding and calculations as you explain in your videos. Hence, it would be nice of cause to have all the possibilities in one application.

**Comment by mmaelicke** [comment]
Ok, then, the error message posted is caused by the CLI, right? I would suggest putting the error message into an issue of its own to discuss and debug it. If there are issues with RStudio, we should switch back to slack and discuss that there. This thread is about a feature request for the hydenv exercises-app. 

Concerning having all possibilities in one application: I think you got a bit confused here: RStudio is a development IDE for R and is developed by the RStudio team. Features and issues in RStudio is nothing I have an influence on (although they are present on github). The hydenv cli is a tool build, especially for the data management lecture. This is where a student was requesting a new feature. The last possibility was to use SQL. This is a query language and not an application at all.

**Comment by mmaelicke** [comment]
With Version `0.9.1` The Schema tree is now available in the console as well.
